export const IS_FETCHING_ON = "IS_FETCHING_ON";
export const IS_FETCHING_OFF = "IS_FETCHING_OFF";

export const MANAGE_MODAL_STATE = "MANAGE_MODAL_STATE";
export const MANAGE_MODAL_CONTENT = "MANAGE_MODAL_CONTENT";