export const SET_DATA = "SET_DATA";
export const SET_AWNSER = "SET_AWNSER";
export const SET_USER_AWNSER = "SET_USER_AWNSER";

export const IS_FETCHING_ON = "IS_FETCHING_ON";
export const IS_FETCHING_OFF = "IS_FETCHING_OFF";

export const MANAGE_MODAL_STATE = "MANAGE_MODAL_STATE";
export const MANAGE_MODAL_CONTENT = "MANAGE_MODAL_CONTENT";
export const MANAGE_MODAL_LOADING = "MANAGE_MODAL_LOADING";